import type { NextPage } from "next";
import Head from "next/head";
import { Hero, Navbar } from "../components/oragnisms";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Super App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <Hero />
    </div>
  );
};

export default Home;
